# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgateway.proto\x12\x07gateway\"q\n\x10\x43reateJobRequest\x12+\n\x08\x64ocument\x18\x01 \x01(\x0b\x32\x19.gateway.DocumentMetadata\x12\x30\n\x0fpipeline_config\x18\x02 \x01(\x0b\x32\x17.gateway.PipelineConfig\"?\n\x10\x44ocumentMetadata\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\" \n\x0ePipelineConfig\x12\x0e\n\x06stages\x18\x01 \x03(\t\"9\n\x0bJobResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\t\"\x1f\n\rGetJobRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t2\x82\x01\n\nJobGateway\x12<\n\tCreateJob\x12\x19.gateway.CreateJobRequest\x1a\x14.gateway.JobResponse\x12\x36\n\x06GetJob\x12\x16.gateway.GetJobRequest\x1a\x14.gateway.JobResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREATEJOBREQUEST']._serialized_start=26
  _globals['_CREATEJOBREQUEST']._serialized_end=139
  _globals['_DOCUMENTMETADATA']._serialized_start=141
  _globals['_DOCUMENTMETADATA']._serialized_end=204
  _globals['_PIPELINECONFIG']._serialized_start=206
  _globals['_PIPELINECONFIG']._serialized_end=238
  _globals['_JOBRESPONSE']._serialized_start=240
  _globals['_JOBRESPONSE']._serialized_end=297
  _globals['_GETJOBREQUEST']._serialized_start=299
  _globals['_GETJOBREQUEST']._serialized_end=330
  _globals['_JOBGATEWAY']._serialized_start=333
  _globals['_JOBGATEWAY']._serialized_end=463
# @@protoc_insertion_point(module_scope)
